### ISSUE TITLE
Bug: Can't create new thread on forums

### ISSUE THREAD

**Issue by thegashlycrumb** [TheWolfA2/Selama#18] opened 2016-07-29 18:05 UTC
I attempted to create a new thread in General Discussion. After completing the thread text and hitting create, the page refreshed, kept my data input, but didn't create a thread. I tried again in the Lore Horde section since it already had a thread, but same result. Using Chrome as a browser if that matters.

**Comment by TheWolfA2** [comment] 2016-07-29 19:30
I just created the Lady Sylvanas thread in "Lore" and had no issues, and I gave myself identical permissions, and am also working from Chrome. Was this attempted from your computer or a mobile device like a phone or tablet? 

Perhaps try logging out and back in again?
If the issue persists let me know!

**Comment by thegashlycrumb** [comment] 2016-07-29 20:02
It appears that the problem may have been that the post was too short. I received an error message on a  reply that was too short but it posted after I added more content. For the new thread, I didn't receive any sort of error message but it did post after adding more content. If possible, we may want to reconsider a 50 character limit.

**Comment by TheWolfA2** [comment] 2016-07-29 21:50
Totally worth discussion! How about a minimum of 1 on thread reply and 25 on an actual thread post?  I'm thinking 1 for the reply because of the traditional "^" reply.

Outside of that, it sounds like the issue is closed aside from needing to modify character minimums

**Closed by TheWolfA2** 2016-07-29 21:50 UTC
Labels: bug

**Comment by thegashlycrumb** [comment] 2016-07-29 23:06
Those character limits sound great.Can we get an error message added if you try to create a thread but don't have the minimum to avoid confusion?

**Comment by TheWolfA2** [comment] 2016-07-30 03:48
That's odd, it should have been displaying error messages already :/ I'm hoping to make a push tonight and hopefully it will fix the issue entirely :D
